#Scan Java libraries for vulnerabilities using OWASP Dependency Check
name: dependency-scan

on: 
    workflow_call:


jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
               distribution: temurin
               java-version: 21

            - name: Verify secret exists
              run: echo "Secret length is ${#NVD_API_KEY}"
              env:
                NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
            
            - name: OWASP Dependency Scan
              run: |
                    mvn org.owasp:dependency-check-maven:check \
                    -DnvdApiKey=${{ secrets.NVD_API_KEY }} \
                    -DnvdApiDelay=6000 \
                    -Dformat=HTML

              