name: Devsecops pipeline

on: 
   push:
      branches: [main]


jobs:

    code-quality:
       uses: ./.github/workflows/code-quality.yml
    
    secrets-scan:
       uses: ./.github/workflows/secrets-scan.yml
       needs: code-quality
       secrets: inherit
    
    sast-scan:
       uses: ./.github/workflows/sast-scan.yml
       needs: secrets-scan

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
        needs: sast-scan
        secrets: inherit
    
    docker-build:
        uses: ./.github/workflows/docker-build.yml
        needs: dependency-scan
        secrets: inherit
    image-scan:
        uses: ./.github/workflows/Image-scan.yml
        needs: docker-build
        secrets: inherit
    
    deploy-to-server:
        uses: ./.github/workflows/deploy-to-server.yml
        needs: image-scan
        secrets: inherit
    #add secrets inherit to all the jobs so that we can use the secrets in any of the job without defining it again and again
    



    
