#check for secrets in the codebase using gitleaks
name: secrets-scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:

            - name : checkout code
              uses: actions/checkout@v4
            
            - name: run git leaks
              uses: gitleaks/gitleaks-action@v2

